name: ArthoDonation
version: 1.0
main: net.arthonetwork.donation.ArthoPlugin
api-version: 1.13
commands:
  don:
    description: Main command for ArthoDonation
    permission: arthodonation.admin
    usage: /don <add|link|reset|reload|help> [args]
  ping:
    description: Check your latency
    usage: /ping
  lag:
    description: Check server or player lag sources
    usage: /lag <joueur|serveur|help>
  server:
    description: Suggestion system
    usage: /server <add|list|remove|help>
  register:
name: Artho-Plugin
version: ${project.version}
main: net.arthonetwork.donation.ArthoPlugin
api-version: 1.13
commands:
  don:
    description: Main command for Artho-Plugin
    permission: arthoplugin.admin
    usage: /don <add|link|reset|reload|help> [args]
  ping:
    description: Check your latency
    usage: /ping
  lag:
    description: Check server or player lag sources
    usage: /lag <joueur|serveur|help>
  server:
    description: Suggestion system
    usage: /server <add|list|remove|help>
  register:
    description: Register an account
    usage: /register <password> <confirm>
  login:
    description: Login to your account
    usage: /login <password>
  auth:
    description: Gérer l'authentification (Admin).
    usage: /auth <subcommand>
    permission: arthoplugin.admin
  changepassword:
    description: Changer son mot de passe.
    usage: /changepassword <nouveau> <confirmation>
  artho:
    description: Afficher l'aide globale du plugin.
    usage: /artho
  arthonetwork:
    description: Afficher l'aide globale du plugin.
    usage: /arthonetwork
