name: Artho-Plugin
version: ${project.version}
main: net.arthonetwork.donation.ArthoPlugin
api-version: 1.13
commands:
  annonces:
    description: Gérer les annonces et donations
    aliases: [don]
    permission: arthoplugin.admin
    usage: /annonces <ajouter|lien|config|reload|aide> [args]
  ping:
    description: Voir sa latence
    usage: /ping [joueur]
  lag:
    description: Voir les infos de lag
    usage: /lag [joueur]
  suggestion:
    description: Système de suggestions
    aliases: [server, idees]
    usage: /suggestion <ajouter|voir|supprimer>
  register:
    description: S'inscrire
    usage: /register <password> <confirm>
  login:
    description: Se connecter
    usage: /login <password>
  auth:
    description: Administration Auth
    usage: /auth <subcommand>
    permission: arthoplugin.admin
  changepassword:
    description: Changer son mot de passe
    usage: /changepassword <nouveau> <confirmation>
  artho:
    description: Aide globale
    usage: /artho
  arthonetwork:
    description: Aide globale
    usage: /arthonetwork
